apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-employee-api
  namespace: apis
spec:
  selector:
    matchLabels:
      app: snyk-employee-api
  replicas: 1
  template:
    metadata:
      labels:
        app: snyk-employee-api
    spec:
      containers:
        - name: snyk-employee-api
          image: pasapples/springbootemployee:jib
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: snyk-employee-api-lb
  namespace: apis
  labels:
    name: snyk-employee-api-lb
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: snyk-employee-api
  type: LoadBalancer
